### ISSUE TITLE
Team06 Review: Keep Requirements Free of Design Decisions

### ISSUE THREAD

**Issue by MichelleDomagala-Tang** [DangJustin/CapstoneProject#12]
Make sure your functional requirements remain abstract and free from design decisions. The SRS document should focus on the _what_ and not the _how_ of the project. Below are some instances of requirements that I'd recommend rewording to make them more abstract. 

- [x] For example, instead of saying "it will have a tile interface" consider changing this requirement to "will display tasks icons on the main page representing different household tasks". Also, each requirement should represent one thing; consider splitting it into: (1) will display icons on the main page for each task type; (2) selecting a task icon will navigate the user to the task management page. 
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/4240a47a-1c4a-4862-bd71-18bdd650f51b)

- [x] Requirement TM3 starts to discuss specifics, like buttons and form fields. A fit criterion lets you check that the requirement has been satisfied, not _how_ it will be satisfied. Something like "once a user creates a task, the same task and details can be viewed on the task management page" doesn't go into the design details and might be a better fit criterion.
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/bcad77d8-aa84-40ad-98c1-470f2c8b6c07)

- [x] Try to keep it abstract, for example "Roommates are able to navigate to the scheduling page from the home interface" instead of including the _how_.
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/489350bb-65e5-433b-9feb-54b36439d7e4)

Great work! Looking forward to reviewing the rest of your team's documents.

Marking TA: @samm82

**Comment by HamidHarris** [comment]
fixed
