### ISSUE TITLE
Explain responsibilities for each system entity on system context diagram - Review-SRS-Team6

### ISSUE THREAD

**Issue by eshaanc20** [DangJustin/CapstoneProject#14]
For the system context diagram that is used to demonstrate scope, it is very hard to determine the scope without stating the responsibilities of each system entity on that diagram. Determining what each system entity needs to do can help build scope and define requirements within that scope. Not knowing what each system entity does can make the scope too big.

<img width="467" alt="Screenshot 2023-10-10 at 9 56 09 PM" src="https://github.com/DangJustin/CapstoneProject/assets/44048100/42cc2225-34fa-41f5-b218-47b1bcdbe63e">

Marking TA: @samm82

**Comment by HamidHarris** [comment]
fixed
