### ISSUE TITLE
SRS TA Feedback

### ISSUE THREAD

**Issue by DangJustin** [DangJustin/CapstoneProject#150]
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/1499b7a7-0a3c-4ae5-8662-cf51d24aa907)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/213974fc-d3dd-4ba0-b5d0-bc85578495e6)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/df3d26fc-ff81-4b63-8014-3e9b72664693)

**Comment by HamidHarris** [comment]
-Fixed general issues with Functional requirements.
-Added and modified relevant Non-functional requirements .
-Added a traceability matrix for functional requirements.
-Added a timeline for development phase.
