### ISSUE TITLE
Hazard Analysis TA Feedback

### ISSUE THREAD

**Issue by DangJustin** [DangJustin/CapstoneProject#151]
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/e275fa31-df0d-4bbf-8c6d-d1964a24d7b6)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/04dacb93-6fa7-42a2-a1fe-c2b9e3ef93f2)

**Comment by FardeenAfsar** [comment]
- [ ] Include more details in roadmap
- [ ] Fix grammatical issues
- [ ] Improve clarity of out-of-scope mitigation hazards
- [ ] Add more requirements and hazards that were missed in first revision 0
