### ISSUE TITLE
Design Documentation TA Feedback

### ISSUE THREAD

**Issue by DangJustin** [DangJustin/CapstoneProject#152]
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/e86f18b3-6436-49c0-a29a-9339566b7f27)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/02f533c0-418e-4291-82e9-648cf8c221a6)

**Comment by Lazarus-XD** [comment]
## Unlikely changes modified
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/e49b51bb-652f-47ac-a3d6-e66a6a2159ce)

## Module decomposition modified
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/ad9a861f-b708-49da-b6c4-475edbf95932)

- Capitalized module names
- Added exception name in access routine semantics
- Stated what conditions cause exception in all specifications
- Added more formal description
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/4861e0b3-1f9f-409d-8066-9d41ed758d1c)
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/2f9d235f-623a-41dc-96f5-92b5207112f0)

**Comment by Lazarus-XD** [comment]
Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
