### ISSUE TITLE
VnV Report TA Feedback

### ISSUE THREAD

**Issue by DangJustin** [DangJustin/CapstoneProject#153]
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/3437cb54-c606-4b55-9e39-01d4cad43924)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/ff4b3eeb-28d5-421f-bbac-9ca2d19e0b3e)
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/587ec5e8-dab0-4a5e-9b44-db618fa89612)

**Comment by fadymorcos21** [comment]
- Added test names to test tables for clarity, short description of results
- Fixed some grammer, syling issues
- Added in depth plans for performance scaling
- Added in depth plans for usability improvement and solutions to address common issues
- Specified more changes to be made
