### ISSUE TITLE
Team 06 VnV Review: Usability survey could be reworded

### ISSUE THREAD

**Issue by cbridel** [DangJustin/CapstoneProject#28]
In your SRS, you mentioned that families could also benefit from your application, but questions 1 and 3 in the usability survey seem specific to people with housemates. If families are also stakeholders, these questions could be phrased more generically, such as "Do you share your home with other people?" and "What do you find frustrating about living with other people?"

![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/2679085e-ed7c-46dc-a0e6-8dfbd6558967)
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/a29b8170-2a30-4a2c-a93f-e7feb24ad05f)

Also, questions 5 to 9 ask the user to give a strict yes or no answer, but for opinion-based questions, sometimes a rating on a scale can be more informative. For example, the user could give a rating on a scale from 0 to 10, similar to [this VnV Plan](https://gitlab.cas.mcmaster.ca/courses/capstone/-/blob/main/SamplesOfStudentWork/VnVPlan/2DPhysicsGameTestPlan.pdf?ref_type=heads) from 2016.

![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/4aee8f3d-16a0-48e8-809c-7863b927cc45)
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/b2eab899-bd29-4671-9444-bae1b1dba45e)

Marking TA: @samm82

**Comment by DangJustin** [comment]
- More quantitative questions have been added as part of revision 1
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/93a677d5-a2fb-4ae5-a842-554d4b80a716)
