### ISSUE TITLE
Team06 VnV Review: Test case labels clarity and consistency

### ISSUE THREAD

**Issue by cbridel** [DangJustin/CapstoneProject#29]
Just wanted to mention, I really liked the system you guys used for labeling your test cases. It makes it easy to tell which requirements map to which test cases.

I noticed that for the bill management system, test cases 1 and 4 cover multiple requirements. When I first saw the labels, I wasn't sure if this meant they were two separate tests or one test covering two requirements. After referencing the traceability matrix, it seems like the tests are separate, since BM5-1 and BM7-1 were split up. It might make it more repetitive, but I think for clarity it would help to split these up instead of combining them.

![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/5afb69b7-768a-45db-9e3b-1510b51118c5)
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/afd47498-985f-43a2-b9ca-5205fcd69f94)
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/9bfc8cd6-c17e-49ab-80d0-f435edaeb9d4)

Also, this doesn't need to be its own issue since it's a minor formatting thing, but test cases 4 and 5 for the bill management system used periods instead of dash separators. Just a small change that would help with consistency.

![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/7d8d8178-761e-4d94-b5f2-38527a803bd8)
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/6e458053-bb3b-4632-b53a-aeb8317c5bae)

Marking TA: @samm82

**Comment by DangJustin** [comment]
- Tests have been renamed as part of revision 1
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/8437120c-c26c-47fa-b82b-fea7265da1aa)
