### ISSUE TITLE
Team06 VnV Review: Objectives Description

### ISSUE THREAD

**Issue by MichelleDomagala-Tang** [DangJustin/CapstoneProject#30]
In the V&V Plan Rubric, it mentions that "the objective should focuses on the most important (mission critical) qualities". The ones your team listed are good, such as ensuring correctness and usability. I would recommend rewording the objectives to focus less on the SRS document, and instead what impact the verification and validation plan would have on your project.
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/4487f809-6b47-4255-b98c-d4438d3f874a)

For example, expanding on the objectives you listed:
1. Ensure the application correctly implements its necessary features. The main goal of Housemates is to allow users to schedule chores, split bills, and delegate tasks. The V&V Plan will allow the team to verify that these features are implemented correctly and in accordance to the SRS.
2. Verify the usability of the Housemates Application, specifically the ease of navigation between pages and learnability.
...

By making these changes you can better define your objectives and the purpose of your V&V Plan.

Marking TA: @samm82

**Comment by DangJustin** [comment]
- Objectives reworded as part of revision 1
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/83ac8128-89fb-4ab9-8db0-531fac84fb91)
