### ISSUE TITLE
Team 06 VnV Review: SRS Verification Plan

### ISSUE THREAD

**Issue by jaymody** [DangJustin/CapstoneProject#32]
In addition to what you already have down for your SRS Verification Plan:

<img width="614" alt="Screenshot 2023-11-07 at 5 30 24 PM" src="https://github.com/DangJustin/CapstoneProject/assets/26451316/ea883dc3-f513-40f3-ad4f-43409c2f6d8e">

I might add a plan to ensure the correctness of the SRS and other documents on requirement changes. That is, if a requirement is updated, it might go out of sync with the traceability matrix, or it may refer to something different when referenced in the test plan, etc ... To ensure correctness, it may be good to assign someone the role of requirements verification who's responsibility is to check the requirements are consistent between documents each time the SRS is updated.

Marking TA: @samm82

**Comment by DangJustin** [comment]
- Updated SRS verification plan as part of revision 1
![image](https://github.com/DangJustin/CapstoneProject/assets/96737543/072cf875-d601-466f-828a-e45ef9ccee4b)
