### ISSUE TITLE
Team 06 VnV Review: Security Tests for Database

### ISSUE THREAD

**Issue by eshaanc20** [DangJustin/CapstoneProject#33]
For the security tests on accessing user data, there is a test for being able to access other user's data through the application user interface but that does not give complete test coverage for data security. Consider adding test coverage for encryption methods on storing the data in the database and possible tests on the backend database not only the user interface. Data can be accessed in the database without going through the application user interface so consider having tests for the database.

<img width="740" alt="Screenshot 2023-11-07 at 10 46 01 PM" src="https://github.com/DangJustin/CapstoneProject/assets/44048100/626bea5a-d60a-4f44-b0db-af034c728b7f">

Marking TA: @samm82

**Comment by DangJustin** [comment]
- Housemates backend databases implemented through Firebase and MongoDB
- As such, we don't feel like tests specifically focused on the database are necessary
