### ISSUE TITLE
Team 06 Design Doc Review: Missing System Design Document

### ISSUE THREAD

**Issue by MichelleDomagala-Tang** [DangJustin/CapstoneProject#40]
The series of design documents should include the MIS, MG, and System Design document. The System Design document seems to be missing. It provides context for undesired event handling, a component diagram, and user interfaces. I would recommend adding it for Revision 1.
Alternatively, you can add a section for undesired event handling and a component diagram in your MG and note the template changes. Similar to how you added a user interfaces section to the Appendix.

![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/75662b13-0496-460d-b81b-282c36cae518)
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/b4d510aa-32cc-47ec-afa2-ec12e96e9502)

Grading TA: @samm82

**Comment by Lazarus-XD** [comment]
Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
