### ISSUE TITLE
Team 06 Design Doc Review: Timeline testing all at the end

### ISSUE THREAD

**Issue by cbridel** [DangJustin/CapstoneProject#42]
Great job on the documents!

One thing I noticed in the timeline in your Module Guide is that it looks like the testing and verification is going to take place after the modules have all been implemented, like a waterfall approach. It might be helpful to also do testing during the implementation so that there's less testing left at the end and potential issues can be caught earlier rather than later.
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/bab0ac4c-b1a4-45bb-90aa-7fdd4f93a0f8)

Marking TA: @samm82

**Comment by Lazarus-XD** [comment]
Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
