### ISSUE TITLE
Team 06 Design Doc Review: Account module (library) has a state variable

### ISSUE THREAD

**Issue by cbridel** [DangJustin/CapstoneProject#43]
According to the design doc checklist, a library module has no state, so it won't have any state or environment variables. The MG says that the Account Module is a library module, but in the MIS, the module has a state variable. Maybe it should be a different type of module?

Checklist:
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/c7d363c2-fb23-4532-b6d2-78cb63fb989e)
MG:
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/7d28a813-8b1c-4053-a821-678a379c9e30)
MIS:
![image](https://github.com/DangJustin/CapstoneProject/assets/10687866/9d2ebcb8-baf6-4f54-ba5e-076facd8a2ef)

Marking TA: @samm82

**Comment by Lazarus-XD** [comment]
# Updated Account Module
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/5aa1be05-a8d5-4b77-be78-b517f5573d1f)

Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
