### ISSUE TITLE
Team 06 Design Doc Review: Missing Module Definitions

### ISSUE THREAD

**Issue by MichelleDomagala-Tang** [DangJustin/CapstoneProject#44]
In your MIS you listed eight modules (five behaviour-hiding modules and three software decision modules), however only defined four.
For example, the interface design module is key in your implementation of housemates and includes state transitions in the UI but is missing in the MIS. Likewise, in the MG it mentions that the database interface module will be implemented by housemates, but details are not provided in the MIS. 
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/5ed886e4-b9b0-4fc3-9d13-334634cb9ea9)
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/d76a24cd-ced7-4998-97e5-20bef4dd8ab0)
![image](https://github.com/DangJustin/CapstoneProject/assets/45515385/40cea006-68d9-4859-9516-f3624f9e2e19)

Grading TA: @samm82

**Comment by Lazarus-XD** [comment]
## Updated Module Decomposition
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/7e72708b-f58c-4207-9af9-9ab418c82e4d)

## Added Database Driver Module
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/0c6f149c-63fa-4ea2-a4a9-318d7dc479d2)

Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
