### ISSUE TITLE
Team 06 Design Doc Review: Avoid unnecessary implementation details

### ISSUE THREAD

**Issue by eshaanc20** [DangJustin/CapstoneProject#45]
When creating high level design documents, it's important to focus on design and not implementation. When designing modules, the functionality of the module is more important than how it's going to be implemented. For example, in these modules don't discuss axios or mongoose because they are protocols and frameworks that are not relevant in a high level design document.

<img width="960" alt="Screenshot 2024-01-21 at 11 29 19 PM" src="https://github.com/DangJustin/CapstoneProject/assets/44048100/21df0a4c-1350-4273-b701-b5b0b6732310">

Marking TA: @samm82

**Comment by Lazarus-XD** [comment]
![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/bd74c75b-5150-42fb-a43d-eb86a8a86eba)

![image](https://github.com/DangJustin/CapstoneProject/assets/38108448/f91945ab-bbdd-4801-8c2e-f39f902513a7)

Commit 034b956809efd31867c5353eab5982001b0112a8 closes this issue
