### ISSUE TITLE
Task Management Module

### ISSUE THREAD

**Issue by DangJustin** [DangJustin/CapstoneProject#49]

**Comment by DangJustin** [comment]
Pages
- Homepage
- Create Task Page
- Tasks Page
- Individual Task Page

Stuff to do
- Setup task data structure

**Comment by DangJustin** [comment]
Change to taskSchema
- add Task Description
- add Deadline Date
form to addTask
- name
- description
- group
- deadline
Integrate tasks page into task management homescreen

**Comment by Lazarus-XD** [comment]
Remove groupID and taskID from schema since MongoDB has _id built-in which can be used for the same purpose

**Comment by DangJustin** [comment]
- Replace groupIDs with the group names when displayed
- Replace userIDs with the user names when displayed
- Maybe show only incomplete tasks and have toggle for completed tasks
