### ISSUE TITLE
Sharer of Costs Specification - Review-SRS-Team6

### ISSUE THREAD

**Issue by jaymody** [DangJustin/CapstoneProject#8]
Hi Team9, 

The SRS is really well done and easy to follow, Figure 2 (usecase diagram) was especially useful to reference when reading the document!

Regarding section 7.5 "Formal Specification of Cost Management System", the function $S$ and set $U$ seems slightly misdefined:

<img width="595" alt="Screenshot 2023-10-10 at 11 54 01 AM" src="https://github.com/DangJustin/CapstoneProject/assets/26451316/9d630cfc-15f6-4b41-82e2-464f1478caef">

For example, I think the statement:

> For users not in $U_i$

was probably meant to be

> If a user $u$ does not share the cost of some item $i$, that is $u \not\in $S(i)$, then $P(i, u) = 0$

This would make more sense since $U$ must contain all users, and the intended message here is "if a user is not a sharer, they owe 0 dollars on that item". It would also make use of $S$, which isn't used anywhere else in the document from my understanding.

Marking TA: @samm82

**Comment by HamidHarris** [comment]
fixed
